import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import NavBar from '../components/ui/NavBar';
import QueryProvider from '@/components/QueryProvider';
import ToasterProvider from '@/components/ToasterProvider';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased justify-center flex`}>
        <QueryProvider>
          <ToasterProvider>
            <NavBar />
            <main className="max-w-[1800px] px-[100px] pt-[80px] w-full">
              {children}
            </main>
          </ToasterProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
